#include "config.h"
#include "ring_buffer.h"
#include "inotify_watcher.h"
#include "log_scanner.h"
#include "webhook_alert.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <chrono>
#include <ctime>
#include <algorithm>
#include <stdexcept>
#include <atomic>
#include <csignal>
#include <cstring>
#include <unordered_map>
#include <sys/stat.h>
#include <pwd.h>
#include <grp.h>
#include <unistd.h>

namespace fs = std::filesystem;

static std::atomic<bool> g_running{true};
static std::atomic<unsigned long> g_alert_count{0};
static std::atomic<unsigned long> g_lines_processed{0};

static void signal_handler(int)
{
    g_running = false;
}

std::string get_timestamp()
{
    auto now = std::chrono::system_clock::now();
    auto time = std::chrono::system_clock::to_time_t(now);
    char buf[64];
    strftime(buf, sizeof(buf), "%Y%m%d_%H%M%S", localtime(&time));
    return buf;
}

std::string get_uptime(time_t start)
{
    time_t now = time(nullptr);
    int diff = static_cast<int>(now - start);
    int days = diff / 86400;
    int hours = (diff % 86400) / 3600;
    int mins = (diff % 3600) / 60;
    int secs = diff % 60;

    std::ostringstream ss;
    if (days > 0)
        ss << days << "d ";
    if (hours > 0 || days > 0)
        ss << hours << "h ";
    if (mins > 0 || hours > 0 || days > 0)
        ss << mins << "m ";
    ss << secs << "s";
    return ss.str();
}

std::string escape_json(const std::string &s)
{
    std::string result;
    for (char c : s)
    {
        switch (c)
        {
        case '"': result += "\\\""; break;
        case '\\': result += "\\\\"; break;
        case '\n': result += "\\n"; break;
        case '\r': result += "\\r"; break;
        case '\t': result += "\\t"; break;
        default: result += c;
        }
    }
    return result;
}

void write_incident(const Config &config, const std::string &keyword,
                    const std::vector<std::string> &context,
                    const std::vector<std::string> &trailing)
{
    fs::create_directories(config.incident_dir);

    std::string filename = config.incident_dir + "/incident_" + get_timestamp() + ".log";
    std::ofstream out(filename);

    out << "=== SHOCKWAKE-LOG INCIDENT REPORT ===\n";
    out << "Timestamp: " << get_timestamp() << "\n";
    out << "Trigger: " << keyword << "\n";
    out << "Log File: " << config.log_path << "\n";
    out << "=====================================\n\n";

    out << "--- PRE-TRIGGER CONTEXT ---\n";
    for (const auto &line : context)
        out << line << "\n";

    out << "\n--- TRIGGER LINE ---\n";
    out << ">>> " << keyword << " DETECTED <<<\n";

    out << "\n--- POST-TRIGGER CONTEXT ---\n";
    for (const auto &line : trailing)
        out << line << "\n";

    out.close();
    std::cout << "[INCIDENT] Saved: " << filename << "\n";
}

std::string build_webhook_payload(const std::string &keyword,
                                  const std::string &log_file,
                                  const std::string &incident_file)
{
    std::ostringstream json;
    json << "{\"content\": \"";
    json << "\xF0\x9F\x9A\xA8 **SHOCKWAKE-LOG ALERT**\\n";
    json << "Trigger: " << escape_json(keyword) << "\\n";
    json << "Log: " << escape_json(log_file) << "\\n";
    json << "Incident: " << escape_json(incident_file) << "\"";
    json << "}";
    return json.str();
}

bool drop_privileges(const std::string &username)
{
    struct passwd *pw = getpwnam(username.c_str());
    if (!pw)
    {
        std::cerr << "Error: Unknown user: " << username << "\n";
        return false;
    }

    uid_t current_uid = getuid();
    if (current_uid == pw->pw_uid)
    {
        std::cout << "[SHOCKWAKE-LOG] Already running as " << username << "\n";
        return true;
    }

    if (current_uid != 0)
    {
        std::cerr << "Warning: Not root, cannot drop privileges to " << username << "\n";
        return true;
    }

    if (setgroups(0, nullptr) != 0)
    {
        std::cerr << "Error: setgroups failed: " << strerror(errno) << "\n";
        return false;
    }

    if (setgid(pw->pw_gid) != 0)
    {
        std::cerr << "Error: setgid failed: " << strerror(errno) << "\n";
        return false;
    }

    if (setuid(pw->pw_uid) != 0)
    {
        std::cerr << "Error: setuid failed: " << strerror(errno) << "\n";
        return false;
    }

    return true;
}

// ─── Subcommand: init ──────────────────────────────────────────────

int cmd_init()
{
    std::string conf = ".shockwake-log.conf";
    if (fs::exists(conf)) {
        std::cout << "Warning: " << conf << " already exists. Skipping.\n";
        return 0;
    }

    std::ofstream out(conf);
    out << "# shockwake-log configuration\n"
        << "# Generated by: shockwake-log init\n\n"
        << "# Log file to monitor (auto-discovered if omitted)\n"
        << "# log = /var/log/syslog\n\n"
        << "# Triggers: comma-separated keywords or regex patterns\n"
        << "triggers = FATAL,ERROR,WARN\n\n"
        << "# Exclusions: lines matching these are skipped\n"
        << "# excludes = DEBUG,healthcheck\n\n"
        << "# Webhook URL (Slack, Discord, etc.)\n"
        << "# webhook = https://hooks.slack.com/services/YOUR/WEBHOOK/URL\n\n"
        << "# Ring buffer: lines to keep for context around triggers\n"
        << "window = 100\n\n"
        << "# Lines to capture AFTER the trigger line\n"
        << "trailing = 20\n\n"
        << "# Directory for incident reports\n"
        << "incidents = ./incidents\n\n"
        << "# Cooldown: min seconds between alerts for same trigger (0 = no limit)\n"
        << "cooldown = 60\n\n"
        << "# Max webhook retry attempts on failure (0 = no retry)\n"
        << "retries = 3\n\n"
        << "# Delay between retries in milliseconds\n"
        << "retry_delay = 1000\n\n"
        << "# Drop to this user after opening log (optional, requires root)\n"
        << "# user = syslog\n";
    out.close();

    std::cout << "Created " << conf << " — edit it, then run:\n"
              << "  shockwake-log\n";
    return 0;
}

// ─── Subcommand: status ────────────────────────────────────────────

int cmd_status(const Config &config)
{
    struct stat st;
    bool file_exists = !config.log_path.empty() && (stat(config.log_path.c_str(), &st) == 0);

    std::cout << "=== shockwake-log status ===\n";
    if (!config.config_path.empty())
        std::cout << "  Config file:  " << config.config_path << "\n";
    std::cout << "  Log file:      " << (config.log_path.empty() ? "(none - will auto-discover)" : config.log_path);
    if (file_exists)
        std::cout << " (" << st.st_size << " bytes)";
    else if (!config.log_path.empty())
        std::cout << " (not found)";
    std::cout << "\n";
    std::cout << "  Webhook:       " << (config.webhook_url.empty() ? "(none - local logging only)" : config.webhook_url) << "\n";
    if (!config.webhook_url.empty())
        std::cout << "  Retries:       " << config.max_retries << " (delay: " << config.retry_delay_ms << "ms)\n";
    std::cout << "  Window:        " << config.window_size << " lines\n";
    std::cout << "  Trailing:      " << config.trailing_lines << " lines\n";
    std::cout << "  Incidents:     " << config.incident_dir << "\n";
    std::cout << "  Triggers:      ";
    for (size_t i = 0; i < config.triggers.size(); i++)
    {
        std::cout << config.triggers[i];
        if (i < config.triggers.size() - 1) std::cout << ", ";
    }
    std::cout << "\n";
    if (!config.excludes.empty())
    {
        std::cout << "  Excludes:      ";
        for (size_t i = 0; i < config.excludes.size(); i++)
        {
            std::cout << config.excludes[i];
            if (i < config.excludes.size() - 1) std::cout << ", ";
        }
        std::cout << "\n";
    }
    std::cout << "  Cooldown:      " << (config.cooldown_seconds > 0 ? std::to_string(config.cooldown_seconds) + "s" : "none") << "\n";
    if (!config.drop_user.empty())
        std::cout << "  Drop user:     " << config.drop_user << "\n";
    std::cout << "============================\n";
    return 0;
}

// ─── Subcommand: incidents ─────────────────────────────────────────

int cmd_incidents(const Config &config)
{
    std::string dir = config.incident_dir;

    if (!fs::exists(dir) || !fs::is_directory(dir)) {
        std::cout << "No incidents yet.\n";
        return 0;
    }

    std::vector<fs::directory_entry> log_files;
    for (const auto& entry : fs::directory_iterator(dir)) {
        if (entry.is_regular_file()) {
            std::string ext = entry.path().extension().string();
            if (ext == ".log") log_files.push_back(entry);
        }
    }

    if (log_files.empty()) {
        std::cout << "No incidents yet.\n";
        return 0;
    }

    // Sort by modification time (newest first)
    std::sort(log_files.begin(), log_files.end(), [](const auto& a, const auto& b) {
        return fs::last_write_time(a) > fs::last_write_time(b);
    });

    std::cout << "Recent incidents:\n\n";
    size_t count = std::min(log_files.size(), static_cast<size_t>(10));
    for (size_t i = 0; i < count; i++) {
        auto ftime = fs::last_write_time(log_files[i]);
        auto sctp = std::chrono::time_point_cast<std::chrono::system_clock::duration>(
            ftime - fs::file_time_type::clock::now() + std::chrono::system_clock::now());
        std::time_t tt = std::chrono::system_clock::to_time_t(sctp);

        char timebuf[64];
        strftime(timebuf, sizeof(timebuf), "%Y-%m-%d %H:%M:%S", localtime(&tt));

        struct stat st;
        stat(log_files[i].path().c_str(), &st);

        std::cout << "  " << timebuf << "  " << st.st_size << " bytes  " << log_files[i].path().string() << "\n";
    }
    std::cout << "\nTotal: " << log_files.size() << " incident(s)\n";
    return 0;
}

// ─── Subcommand: logs ──────────────────────────────────────────────

int cmd_logs(const Config &config)
{
    std::string dir = config.incident_dir;

    if (!fs::exists(dir) || !fs::is_directory(dir)) {
        std::cerr << "No incidents yet. Start monitoring first.\n";
        return 1;
    }

    // Find most recent incident file
    std::string latest;
    fs::file_time_type latest_time{};

    for (const auto& entry : fs::directory_iterator(dir)) {
        if (!entry.is_regular_file()) continue;
        std::string ext = entry.path().extension().string();
        if (ext != ".log") continue;

        auto ftime = fs::last_write_time(entry);
        if (latest.empty() || ftime > latest_time) {
            latest = entry.path().string();
            latest_time = ftime;
        }
    }

    if (latest.empty()) {
        std::cerr << "No incidents yet. Start monitoring first.\n";
        return 1;
    }

    std::cout << "Following: " << latest << "\n";
    std::cout << "(Press Ctrl+C to stop)\n\n";

    // Open and tail the file
    std::ifstream file(latest);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open " << latest << "\n";
        return 1;
    }

    // Read to end first
    file.seekg(0, std::ios::end);
    while (g_running) {
        std::string line;
        if (std::getline(file, line)) {
            std::cout << line << "\n";
        } else {
            // Check for new content
            auto pos = file.tellg();
            file.clear();
            file.seekg(0, std::ios::end);
            auto end = file.tellg();
            if (pos == end) {
                // No new content, wait
                file.clear();
                file.seekg(pos);
                usleep(500000); // 500ms
            }
        }
    }

    return 0;
}

// ─── Subcommand: stop ──────────────────────────────────────────────

int cmd_stop(const Config &config)
{
    std::string pid_file = config.pid_file;

    if (pid_file.empty() || !fs::exists(pid_file)) {
        std::cerr << "No PID file found. Is shockwake-log running?\n";
        std::cerr << "If running as a systemd service: sudo systemctl stop shockwake-log\n";
        return 1;
    }

    std::ifstream pf(pid_file);
    std::string pid_str;
    std::getline(pf, pid_str);
    pf.close();

    if (pid_str.empty()) {
        std::cerr << "PID file is empty. Removing stale file.\n";
        fs::remove(pid_file);
        return 1;
    }

    pid_t pid = std::stoi(pid_str);

    if (kill(pid, 0) != 0) {
        std::cerr << "Process " << pid << " is not running. Cleaning up.\n";
        fs::remove(pid_file);
        return 0;
    }

    std::cout << "Stopping shockwake-log (PID " << pid << ")...\n";
    kill(pid, SIGTERM);
    sleep(1);

    if (kill(pid, 0) == 0) {
        std::cout << "Process still alive, sending SIGKILL...\n";
        kill(pid, SIGKILL);
    }

    fs::remove(pid_file);
    std::cout << "Stopped.\n";
    return 0;
}

// ─── Subcommand: clean ─────────────────────────────────────────────

int cmd_clean(const Config &config)
{
    // Stop if running
    std::string pid_file = config.pid_file;
    if (!pid_file.empty() && fs::exists(pid_file)) {
        std::ifstream pf(pid_file);
        std::string pid_str;
        std::getline(pf, pid_str);
        pf.close();

        if (!pid_str.empty()) {
            pid_t pid = std::stoi(pid_str);
            if (kill(pid, 0) == 0) {
                std::cout << "Stopping monitor (PID " << pid << ")...\n";
                kill(pid, SIGTERM);
                sleep(1);
            }
        }
        fs::remove(pid_file);
    }

    // Remove incidents
    std::string dir = config.incident_dir;
    if (fs::exists(dir)) {
        std::cout << "Cleaning " << dir << "...\n";
        fs::remove_all(dir);
    }

    std::cout << "Done.\n";
    return 0;
}

// ─── Subcommand: monitor ───────────────────────────────────────────

int cmd_monitor(Config &config)
{
    if (config.log_path.empty()) {
        std::cerr << "Error: No log file specified and none found via auto-discovery.\n";
        std::cerr << "Use --help for usage.\n";
        return 1;
    }

    if (!config.webhook_url.empty())
        std::cout << "[SHOCKWAKE-LOG] Webhook enabled: " << config.webhook_url << "\n";
    else
        std::cout << "[SHOCKWAKE-LOG] No webhook configured — alerts will be logged locally only.\n";

    if (!config.config_path.empty())
        std::cout << "[SHOCKWAKE-LOG] Config loaded: " << config.config_path << "\n";

    struct stat st;
    if (stat(config.log_path.c_str(), &st) != 0) {
        std::cerr << "Error: Log file does not exist: " << config.log_path << "\n";
        return 1;
    }

    // Write PID file
    std::string pid_file = config.pid_file.empty() ? "./.shockwake-log.pid" : config.pid_file;
    {
        std::ofstream pf(pid_file);
        pf << getpid();
    }

    // Clean up PID on exit
    auto cleanup_pid = [&pid_file]() {
        fs::remove(pid_file);
    };

    std::signal(SIGTERM, signal_handler);
    std::signal(SIGINT, signal_handler);

    InotifyWatcher watcher(config.log_path);
    RingBuffer buffer(config.window_size);
    LogScanner scanner;
    scanner.set_triggers(config.triggers);
    scanner.set_excludes(config.excludes);

    bool has_webhook = !config.webhook_url.empty();
    WebhookAlert alerter(config.webhook_url, config.max_retries, config.retry_delay_ms);
    if (has_webhook)
        alerter.start();

    if (!config.drop_user.empty())
    {
        if (!drop_privileges(config.drop_user))
        {
            if (has_webhook) alerter.stop();
            cleanup_pid();
            return 1;
        }
        std::cout << "[SHOCKWAKE-LOG] Dropped privileges to: " << config.drop_user << "\n";
    }

    std::cout << "[SHOCKWAKE-LOG] Starting...\n";
    std::cout << "  Log file:    " << config.log_path << "\n";
    std::cout << "  Webhook:     " << (has_webhook ? "enabled" : "disabled (local only)") << "\n";
    if (has_webhook)
        std::cout << "  Retries:     " << config.max_retries << " (delay: " << config.retry_delay_ms << "ms)\n";
    std::cout << "  Window:      " << config.window_size << " lines\n";
    std::cout << "  Trailing:    " << config.trailing_lines << " lines\n";
    std::cout << "  Triggers:    ";
    for (size_t i = 0; i < config.triggers.size(); i++)
    {
        std::cout << config.triggers[i];
        if (i < config.triggers.size() - 1) std::cout << ", ";
    }
    std::cout << "\n";
    if (!config.excludes.empty())
    {
        std::cout << "  Excludes:    ";
        for (size_t i = 0; i < config.excludes.size(); i++)
        {
            std::cout << config.excludes[i];
            if (i < config.excludes.size() - 1) std::cout << ", ";
        }
        std::cout << "\n";
    }
    std::cout << "  Cooldown:    " << (config.cooldown_seconds > 0 ? std::to_string(config.cooldown_seconds) + "s" : "none") << "\n";
    std::cout << "[SHOCKWAKE-LOG] Watching for changes...\n\n";

    time_t start_time = time(nullptr);
    time_t last_health_log = start_time;
    std::unordered_map<std::string, time_t> last_alert_time;
    std::unordered_map<std::string, unsigned long> suppressed_count;

    while (g_running)
    {
        std::string new_content = watcher.wait_for_changes();
        if (new_content.empty())
            continue;

        time_t now = time(nullptr);
        if (now - last_health_log >= 60)
        {
            std::cout << "[HEALTH] uptime=" << get_uptime(start_time)
                      << " alerts=" << g_alert_count.load()
                      << " lines=" << g_lines_processed.load() << "\n";
            last_health_log = now;
        }

        std::istringstream stream(new_content);
        std::string line;
        while (std::getline(stream, line))
        {
            if (line.empty())
                continue;

            buffer.push(line);
            g_lines_processed++;

            if (scanner.scan(line))
            {
                std::string keyword = scanner.matched_keyword();

                time_t now2 = time(nullptr);
                if (config.cooldown_seconds > 0 && last_alert_time.count(keyword))
                {
                    int elapsed = static_cast<int>(now2 - last_alert_time[keyword]);
                    if (elapsed < config.cooldown_seconds)
                    {
                        suppressed_count[keyword]++;
                        continue;
                    }
                }

                std::cout << "[TRIGGER] " << keyword << " detected!\n";

                auto pre_context = buffer.snapshot();
                auto post_context = buffer.tail(config.trailing_lines);

                write_incident(config, keyword, pre_context, post_context);

                std::string incident_file = config.incident_dir + "/incident_" + get_timestamp() + ".log";
                if (has_webhook)
                {
                    std::string payload = build_webhook_payload(keyword, config.log_path, incident_file);
                    alerter.enqueue(payload);
                    std::cout << "[ALERT] Webhook fired.\n\n";
                }
                else
                {
                    std::cout << "[ALERT] Incident logged locally.\n\n";
                }

                g_alert_count++;
                last_alert_time[keyword] = time(nullptr);
            }
        }
    }

    std::cout << "\n[SHOCKWAKE-LOG] Shutting down...\n";
    std::cout << "[SHOCKWAKE-LOG] Uptime: " << get_uptime(start_time)
              << " | Alerts: " << g_alert_count.load()
              << " | Lines: " << g_lines_processed.load() << "\n";
    if (has_webhook && alerter.dropped_count() > 0)
        std::cout << "[SHOCKWAKE-LOG] Dropped alerts: " << alerter.dropped_count() << "\n";

    unsigned long total_suppressed = 0;
    for (const auto &[kw, count] : suppressed_count)
        total_suppressed += count;
    if (total_suppressed > 0)
        std::cout << "[SHOCKWAKE-LOG] Suppressed by cooldown: " << total_suppressed << "\n";

    if (has_webhook)
        alerter.stop();

    cleanup_pid();
    return 0;
}

// ─── Main dispatch ─────────────────────────────────────────────────

int main(int argc, char *argv[])
{
    Config config = parse_args(argc, argv);

    switch (config.subcommand)
    {
    case SubCommand::INIT:
        return cmd_init();
    case SubCommand::STATUS:
        return cmd_status(config);
    case SubCommand::INCIDENTS:
        return cmd_incidents(config);
    case SubCommand::LOGS:
        return cmd_logs(config);
    case SubCommand::STOP:
        return cmd_stop(config);
    case SubCommand::CLEAN:
        return cmd_clean(config);
    case SubCommand::MONITOR:
    default:
        return cmd_monitor(config);
    }
}
