#include "subcommands.h"
#include "utilities.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <algorithm>
#include <chrono>
#include <csignal>
#include <cstring>
#include <sys/stat.h>
#include <unistd.h>

namespace fs = std::filesystem;

int cmd_init()
{
    std::string conf = ".swl.conf";
    if (fs::exists(conf)) {
        std::cout << "warning: " << conf << " already exists. skipping.\n";
        return 0;
    }

    std::ofstream out(conf);
    out << "# swl configuration\n"
        << "# Generated by: swl init\n\n"
        << "# log file to monitor (auto-discovered if omitted)\n"
        << "# log = /var/log/syslog\n\n"
        << "# triggers: comma-separated keywords or regex patterns\n"
        << "triggers = FATAL,ERROR,WARN\n\n"
        << "# exclusions: lines matching these are skipped\n"
        << "# excludes = DEBUG,healthcheck\n\n"
        << "# webhook url (slack, discord, etc.)\n"
        << "# webhook = https://hooks.slack.com/services/YOUR/WEBHOOK/URL\n\n"
        << "# ring buffer: lines to keep for context around triggers\n"
        << "window = 100\n\n"
        << "# lines to capture after the trigger line\n"
        << "trailing = 20\n\n"
        << "# directory for incident reports\n"
        << "incidents = /var/log/swl-incidents\n\n"
        << "# cooldown: min seconds between alerts for same trigger (0 = no limit)\n"
        << "cooldown = 60\n\n"
        << "# max webhook retry attempts on failure (0 = no retry)\n"
        << "retries = 3\n\n"
        << "# delay between retries in milliseconds\n"
        << "retry_delay = 1000\n\n"
        << "# drop to this user after opening log (optional, requires root)\n"
        << "# user = syslog\n\n"
        << "# disable ssl certificate verification for self-signed certs\n"
        << "# ssl_verify = true\n\n"
        << "# max characters per log line (longer lines are truncated)\n"
        << "# max_line_length = 8192\n";
    out.close();

    std::cout << "created " << conf << " — edit it, then run:\n"
              << "  swl\n";
    return 0;
}

int cmd_incidents(const Config &config)
{
    std::string dir = config.incident_dir;

    if (!fs::exists(dir) || !fs::is_directory(dir)) {
        std::cout << "no incidents yet.\n";
        return 0;
    }

    std::vector<fs::directory_entry> log_files;
    for (const auto& entry : fs::directory_iterator(dir)) {
        if (entry.is_regular_file()) {
            std::string ext = entry.path().extension().string();
            if (ext == ".log") log_files.push_back(entry);
        }
    }

    if (log_files.empty()) {
        std::cout << "no incidents yet.\n";
        return 0;
    }

    std::sort(log_files.begin(), log_files.end(), [](const auto& a, const auto& b) {
        return fs::last_write_time(a) > fs::last_write_time(b);
    });

    std::cout << "recent incidents:\n\n";
    size_t count = std::min(log_files.size(), static_cast<size_t>(10));
    for (size_t i = 0; i < count; i++) {
        auto ftime = fs::last_write_time(log_files[i]);
        auto sctp = std::chrono::time_point_cast<std::chrono::system_clock::duration>(
            ftime - fs::file_time_type::clock::now() + std::chrono::system_clock::now());
        std::time_t tt = std::chrono::system_clock::to_time_t(sctp);

        char timebuf[64];
        strftime(timebuf, sizeof(timebuf), "%Y-%m-%d %H:%M:%S", localtime(&tt));

        struct stat st;
        stat(log_files[i].path().c_str(), &st);

        std::cout << "  " << timebuf << "  " << st.st_size << " bytes  " << log_files[i].path().string() << "\n";
    }
    std::cout << "\nTotal: " << log_files.size() << " incident(s)\n";
    return 0;
}

int cmd_logs(const Config &config)
{
    std::string dir = config.incident_dir;

    if (!fs::exists(dir) || !fs::is_directory(dir)) {
        std::cerr << "no incidents yet. start monitoring first.\n";
        return 1;
    }

    std::string latest;
    fs::file_time_type latest_time{};

    for (const auto& entry : fs::directory_iterator(dir)) {
        if (!entry.is_regular_file()) continue;
        std::string ext = entry.path().extension().string();
        if (ext != ".log") continue;

        auto ftime = fs::last_write_time(entry);
        if (latest.empty() || ftime > latest_time) {
            latest = entry.path().string();
            latest_time = ftime;
        }
    }

    if (latest.empty()) {
        std::cerr << "no incidents yet. start monitoring first.\n";
        return 1;
    }

    std::cout << "following: " << latest << "\n";
    std::cout << "(Press Ctrl+C to stop)\n\n";

    std::ifstream file(latest);
    if (!file.is_open()) {
        std::cerr << "error: cannot open " << latest << "\n";
        return 1;
    }

    std::signal(SIGINT, [](int) {
        std::cout << std::flush;
        _exit(0);
    });

    file.seekg(0, std::ios::end);

    while (g_running) {
        std::streampos pos_before = file.tellg();

        std::string line;
        if (std::getline(file, line)) {
            std::cout << line << "\n" << std::flush;
        } else {
            file.clear();

            file.seekg(0, std::ios::end);
            std::streampos end_pos = file.tellg();

            if (pos_before >= std::streampos(0) && pos_before < end_pos) {
                file.seekg(pos_before);
            } else {
                usleep(500000);
            }
        }
    }

    return 0;
}

int cmd_stop(const Config &config)
{
    std::string pid_file = config.pid_file;

    if (pid_file.empty() || !fs::exists(pid_file)) {
        std::cerr << "no pid file found. is swl running?\n";
        std::cerr << "if running as a systemd service: sudo systemctl stop swl\n";
        return 1;
    }

    pid_t pid = read_pid_file(pid_file);

    if (pid == 0) {
        std::ifstream pf(pid_file);
        std::string pid_str;
        std::getline(pf, pid_str);
        pf.close();

        if (pid_str.empty()) {
            std::cerr << "pid file is empty. removing stale file.\n";
        } else {
            std::cerr << "process is not running. cleaning up.\n";
        }
        fs::remove(pid_file);
        return 1;
    }

    std::cout << "stopping swl (pid " << pid << ")...\n";
    kill(pid, SIGTERM);
    sleep(1);

    if (kill(pid, 0) == 0) {
        std::cout << "process still alive, sending sigkill...\n";
        kill(pid, SIGKILL);
    }

    fs::remove(pid_file);
    std::cout << "stopped.\n";
    return 0;
}

int cmd_clean(const Config &config)
{
    std::string pid_file = config.pid_file;
    if (!pid_file.empty() && fs::exists(pid_file)) {
        pid_t pid = read_pid_file(pid_file);
        if (pid > 0) {
            std::cout << "stopping monitor (pid " << pid << ")...\n";
            kill(pid, SIGTERM);
            sleep(1);
        }
        fs::remove(pid_file);
    }

    std::string dir = config.incident_dir;
    if (fs::exists(dir)) {
        std::cout << "cleaning " << dir << "...\n";
        fs::remove_all(dir);
    }

    std::cout << "done.\n";
    return 0;
}
